-- 문제: 평균 일일 대여 요금 구하기
-- 레벨: 1
-- 링크: https://school.programmers.co.kr/learn/courses/30/lessons/151136
--
-- CAR_RENTAL_COMPANY_CAR 테이블에서 자동차 종류가 'SUV'인 자동차들의 평균 일일 대여 요금을 출력하는 SQL문을 작성해주세요.
-- 이때 평균 일일 대여 요금은 소수 첫 번째 자리에서 반올림하고, 컬럼명은 AVERAGE_FEE로 지정해주세요.
--
-- 힌트: ROUND, AVG 함수 사용
-- WEEK5: 여기에 SQL 쿼리를 작성하세요