-- 문제: 상품 별 오프라인 매출 구하기
-- 레벨: 2
-- 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131533
--
-- PRODUCT 테이블과 OFFLINE_SALE 테이블에서 상품코드 별 매출액(판매가 * 판매량) 합계를 출력하는 SQL문을 작성해주세요.
-- 결과는 매출액을 기준으로 내림차순 정렬해주시고 매출액이 같다면 상품코드를 기준으로 오름차순 정렬해주세요.
--
-- 힌트:
-- PRODUCT와 OFFLINE_SALE 테이블을 PRODUCT_ID로 JOIN
-- WEEK5: 여기에 SQL 쿼리를 작성하세요